### ISSUE TITLE
Speech dates

### ISSUE THREAD

**Issue by mlinegar** [PedramNavid/trump_speeches#3]
Do you have information about when each of these speeches were given? I'd like to be able to place them in time as well as place.

**Comment by ZaydH** [comment]
The tool scrapes from here:

http://www.presidency.ucsb.edu/2016_election_speeches.php?candidate=45&campaign=2016TRUMP&doctype=5000

It would not be hard to modify the script to add the dates to the files.  If you need help, let me know.
